### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by sofiapillai87** [Shikhargupta/Machine-Learning-and-Pattern-Recognition#1]
```
Traceback (most recent call last):
  File "ml.py", line 49, in <module>
    cov2 = cov2 + (features[x] - mu2).transpose()*(features[x] - mu2)
  File "/usr/lib/python2.7/dist-packages/numpy/matrixlib/defmatrix.py", line 318, in __getitem__
    out = N.ndarray.__getitem__(self, index)
IndexError: index 301 is out of bounds for axis 0 with size 301
```

kindly resolve the problem

**Comment by agoel00** [comment]
The indexing starts at 0. Since the size is 301 the index range is [0, 1, 2, ...., 300]

I think that's why the error occurs.
